import { Html, Main, Head, NextScript } from 'next/document'
import React from 'react'

type Props = {}

function _head({}: Props) {
  return (
    <Html lang="en">
      <Head>
        <title>Masjid Bilal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mosque.ico" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}

export default _head
